name: deploy preview

on:
  pull_request:
    branch:
      - main
      - dev
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: to preview branch

      - name: Check if comment exists
        id: check-comment
        run: |
          echo "::set-output name=comment-exists::${{ steps.find-comment.outputs.comment-id != '' }}"

      - name: Create comment if does not exist
        id: create-comment
        uses: peter-evans/create-or-update-comment@v3
        if: steps.check-comment.outputs.comment-exists == 'false'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: 'Creating comment because none exists yet.'

      - name: Get comment ID
        id: get-comment-id
        run: |
          echo "::set-output name=comment-id::${{ steps.find-comment.outputs.comment-id != '' && steps.find-comment.outputs.comment-id || steps.create-comment.outputs.comment-id }}"

      - name: comment on PR, deploy to preview
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.get-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: >
            ğŸ“º Deploy to preview branch ğŸ“º
          edit-mode: replace

      - name: comment on PR, install packages
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.get-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: >
            â­ Install packages...

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: comment on PR, building app
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.get-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: >
            ğŸ”¨ Building app...

      - name: set branch name and build directory
        id: branch_directory
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF##*/}
          echo "Branch name: $BRANCH_NAME"
          echo "Build directory: preview/$BRANCH_NAME"
          echo "::set-output name=build_directory::preview/$BRANCH_NAME"
          echo "::set-output name=build_directory_without_base::$BRANCH_NAME"

      - name: build App
        run: |
          yarn build

      - name: comment on PR, doing deploy
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.get-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: >
            ğŸ§‘â€ğŸ’» Start deploy...

      - name: deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gabrielogregorio/mfe-layout.git
          mkdir -p preview/${{ steps.branch_directory.outputs.build_directory }}
          cp -r dist/* preview/${{ steps.branch_directory.outputs.build_directory }}
          npx gh-pages -d preview --add -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current time
        id: currentTime
        run: echo "::set-output name=current_time::$(date +'%d-%m-%Y-%H.%M:%S')"
        shell: bash

      - name: comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.get-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: >
            ğŸš€ The deploy will be done in https://gabrielogregorio.github.io/mfe-layout/preview/${{ steps.branch_directory.outputs.build_directory_without_base }}/mfe-layout.js?nocache=${{ steps.currenttime.outputs.current_time }}
